[profile.default]
src = "src"
out = "out"
libs = ["lib"]

#Remap the location of @chainlink to where the file is now located
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config